FIX: Mac OS X fixes: mostly gmp-related...

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -136,17 +136,21 @@ fi
 LB_MISC
 LB_DRIVER
 
+
+LB_CHECK_GMP(3.1.1,,AC_MSG_ERROR([Unable to find GMP on your machine: please use --with-gmp=PATH_TO_DIR_CONTAINING_LIB_AND_INCLUDE (see also ./configure --help if you do not understand what we are talking about)]))
+
+#LB_CHECK_GMP(,,[
+#echo '*******************************************************************************'
+#echo ' ERROR: GMP not found!'
+#echo
+#echo ' GMP version 3.1.1 or greater with --enable-cxx is required for this library to compile. Please'
+#echo ' make sure GMP is installed and specify its location with the option'
+#echo ' --with-gmp=<prefix> when running configure.'
+#echo '*******************************************************************************'
+#exit 1
+#])
+
 AC_LANG_CPLUSPLUS
-LB_CHECK_GMP(,,[
-echo '*******************************************************************************'
-echo ' ERROR: GMP not found!'
-echo
-echo ' GMP version 3.1.1 or greater with --enable-cxx is required for this library to compile. Please'
-echo ' make sure GMP is installed and specify its location with the option'
-echo ' --with-gmp=<prefix> when running configure.'
-echo '*******************************************************************************'
-exit 1
-])
 
 LB_CHECK_MAPLE
 LB_CHECK_SAGE
